Factory/Models/DesignTimeDbContextFactory.cs
using System;
using System.IO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using Factory.Models;

namespace Factory.Models
{
  public class FactoryContextFactory:IDesignTimeDbContextFactory<FactoryContext>
  {
		FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace Factory.Models
{
	public class Engineer
	{
		public Engineer(){
			this.JoinEntities = new HashSet<EngineerMachine>();
		}
		[Key]
		public int EId {get;set;}

		public string EName {get;set;}

		public string EExperience {get;set;}

		public virtual ICollection<EngineerMachine> JoinEntities{get;set;}
	}

}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
	public class EngineerMachine
	{
		public int EngineerMachineId {get;set;}

		public int MId {get;set;}
		public virtual Machine Machine {get;set;}

		public virtual Engineer Engineer {get;set;}
		public int EId {get;set;}
	}
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public DbSet<Engineer> Engineers { get; set; }

    public DbSet<Machine> Machines { get; set; }

    public DbSet<EngineerMachine> EngineerMachine { get; set;}
  
    public FactoryContext(DbContextOptions options):base(options) {}
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace Factory.Models
{
	public class Machine
	{
		public Machine(){
			this.JoinEntities = new HashSet<EngineerMachine>();
		}
		[Key]
		public int MId {get;set;}
		public string MName {get;set;}
		public virtual ICollection<EngineerMachine> JoinEntities{get;set;}
	}
}

Factory/Controllers/EngineersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Factory.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace Factory.Controllers
{
	public class EngineersController : Controller 
	{
		private readonly FactoryContext _db;

		public EngineersController(FactoryContext db)
		{
			_db = db;
		}

			public ActionResult Index()
		{
			return View(_db.Engineers.ToList());
		}

		public ActionResult Create()
		{
		return View("Create", "engineers");
		}

		[HttpPost]
		public ActionResult Create(Engineer engineer)
		{
			_db.Engineers.Add(engineer);
			_db.SaveChanges();
			return RedirectToAction("Index", "engineers");
		}

		public ActionResult Details(int id)
		{
			var thisEngineer = _db.Engineers
			.Include(engineer=> engineer.JoinEntities)
			.ThenInclude(join => join.Machine)
			.FirstOrDefault(engineer=> engineer.EId == id);
			return View(thisEngineer);
		}
		public ActionResult Edit(int id)
		{
			var thisEngineer = _db.Engineers.FirstOrDefault(engineer=> engineer.EId == id);
			return View(thisEngineer);
		}

	[HttpPost]
	public ActionResult Edit(Engineer engineer)
	{
		_db.Entry(engineer).State = EntityState.Modified;
		_db.SaveChanges();
		return RedirectToAction("Index");
		}
		public ActionResult Delete (int id)
			{
				var thisEngineer = 
				_db.Engineers.FirstOrDefault(engineer => engineer.EId == id);
				return View(thisEngineer);
			}
		[HttpPost, ActionName("Delete")]
			public ActionResult DeleteConfirmed(int id)
			{
				var thisEngineer = 
				_db.Engineers.FirstOrDefault(engineer=> engineer.EId == id);
				_db.Engineers.Remove(thisEngineer);
				_db.SaveChanges();
				return RedirectToAction("Index");
			}
		public ActionResult AddM(int id)
		{
			var thisEngineer =
			_db.Engineers.FirstOrDefault(engineer => engineer.EId == id );
			return View(thisEngineer);
		}

		[HttpPost]
		public ActionResult AddM(Engineer engineer, int MId)
		{
			if (MId !=0)
			{
				_db
					.EngineerMachine
					.Add(new EngineerMachine()
					{MId =MId, EId = engineer.EId});
				_db.SaveChanges();
			}
			return RedirectToAction("Index");
			}

	}
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Factory.Controllers
{
	public class HomeController : Controller
	{
		[HttpGet("/")]
		public ActionResult Index()
		{
			return View();
		}
	}
}

Factory/Controllers/MachinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Factory.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Factory.Controllers
{
	public class MachinesController : Controller
	{
		private readonly FactoryContext _db;

		public MachinesController(FactoryContext db)
		{
			_db = db;
		}
		public ActionResult Index()
		{
			return View(_db.Machines.ToList());
		}
		public ActionResult Create()
		{
		ViewBag.EId = new SelectList(_db.Engineers, "EId", "EName");
		return View();
		}
	[HttpPost]
	public ActionResult Create(Machine machine, int EId)
	{
		_db.Machines.Add(machine);
		_db.SaveChanges();
		if (EId != 0)
		{
			_db
				.EngineerMachine
				.Add(new EngineerMachine()
				{EId = EId, MId = machine.MId});
					_db.SaveChanges();
		}
		return RedirectToAction("Index");
	}
	public ActionResult Details (int id)
	{
		var thisMachine =
		_db 
		.Machines 
		.Include (machine=> machine.JoinEntities)
		.ThenInclude(join => join.Engineer)
		.FirstOrDefault(machine => machine.MId == id);
	return View(thisMachine);
	}
	public ActionResult Edit(int id)
	{
		var thisMachine =
		 _db.Machines.FirstOrDefault(machine => machine.MId == id);
		ViewBag.EId = new SelectList(_db.Engineers, "EId", "EName");
		return View(thisMachine);
	}
    [HttpPost]
    public ActionResult Edit(Machine machine, int EId)
    {
      if (EId != 0 && _db.EngineerMachine.FirstOrDefault(_d => _d.EId == EId && _d.MId == machine.MId) == null)
      {
        _db
            .EngineerMachine
            .Add(new EngineerMachine
            { EId = EId, MId = machine.MId });
        _db.SaveChanges();
      }

      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");

		}
  [HttpPost]
	public ActionResult Delete(int id)
	{
		var thisMachine =
		_db.Machines.FirstOrDefault(machine => machine.MId == id);
		return View(thisMachine);
	}
	[HttpPost, ActionName("Delete")]
	public ActionResult DeleteConfirmed(int id)
	{
		var thisMachine = 
		_db.Machines.FirstOrDefault(machine => machine.MId == id);
		_db.Machines.Remove(thisMachine);
		_db.SaveChanges();
		return RedirectToAction("Index");
	}
	public ActionResult AddE(int id)
  {
      var thisMachine =
          _db.Machines.FirstOrDefault(machine => machine.MId == id);
      ViewBag.EId = new SelectList(_db.Engineers, "EId", "EName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddE(Machine machine, int EId)
    {
      if (EId != 0)
      {
        _db
            .EngineerMachine
            .Add(new EngineerMachine()
            { EId = EId, MId = machine.MId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }
	}

	}

Factory/Views/Engineer/AddE.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h2>Add an Engineer</h2>

<h4> Add Machine Engineer: @Html.DisplayFor(model => model.MName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MId)

    @Html.Label("Select engineer")
    @Html.DropDownList("EId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Add Engineer", "AddE", new { id = Model.MId })</p>

Factory/Views/Engineer/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Add a new Engineer</h4>

@using (Html.BeginForm())
{
<p>Name: @Html.TextBoxFor(model => model.EName)</p>
<p>Years of Experience: @Html.TextBoxFor(model => model.EExperience)</p>
<p>Assigned Machines: <div class="custom-select" style="width200px;"><select>@Html.DropDownList("MId")</select></div>
</p>

  <input type="submit" value="Add new Engineer" />
}

<p>@Html.ActionLink("Show engineers", "Index")</p>

Factory/Views/Engineers/AddE.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add an Engineer</h2>

<h4> Add Machine Engineer: @Html.DisplayFor(model => model.MName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MId)

    @Html.Label("Select engineer")
    @Html.DropDownList("EId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Add Engineer", "AddE", new { id = Model.MId })</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer


<h4>Add a new Engineer</h4>

@using (Html.BeginForm())
{
<p>Name: @Html.TextBoxFor(model => model.EName)</p>
<p>Years of Experience: @Html.TextBoxFor(model => model.EExperience)</p>
<p>Assigned Machines: <div class="custom-select" style="width200px;">
  <select>@Html.DropDownList("MId")</select>
  </div>
</p>

  <input type="submit" value="Add new Engineer" />
}

<p>@Html.ActionLink("Show engineers", "Index")</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.EName): @Html.DisplayFor(model => model.EName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.EName): @Html.DisplayFor(model => model.EName)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This engineer is not assigned to any machines</p>
}
else
{
  <h4>Engineer Info:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Machine.MName</li>
  }
  </ul>

	<h4>Years of Experience:</h4>
	<p>@Html.DisplayNameFor(model => model.EExperience): @Html.DisplayFor(model => model.EExperience)</p>
}

<p>@Html.ActionLink("Back to engineers", "Index")</p>
<p>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EId })</p>
<p>@Html.ActionLink("Delete", "Delete", new { id = Model.EId })</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit Engineer Info:</h2>
<p> For : @Html.DisplayFor(model => model.EName)</p>

@using (Html.BeginForm())
{
	@Html.HiddenFor(model=> model.EId)

	<p>
	Name: @Html.EditorFor(model=> model.EName)

	Machines: 
	@Html.DropDownList("MId")
	</p>

	<input type= "submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@using System.ComponentModel.DataAnnotations;
@model List<Factory.Models.Engineer>


<h1>Engineers</h1>

@if (@Model.Count == 0)
{
  <h3>No Engineers listed! Click <a>@Html.ActionLink("here", "Create")</a> to add a new engineer.
	</h3>
} 

@foreach (Engineer engineer in Model)
{
  <li>@Html.ActionLink($"{engineer.EName}", "Details", new { id = engineer.EId })</li>
}

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}


<p>@Html.ActionLink("See all Machines", "Index", "machines")</p>

<p>@Html.ActionLink("See all Engineers", "Index", "engineers")</p>

Factory/Views/Machines/AddM.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a Machine</h2>

<h4>Add a Machine to this Engineer's Experience: @Html.DisplayFor(model => model.EName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EId)

    @Html.Label("Add Machine")
    @Html.DropDownList("MId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index","Engineer")</p>
<p>@Html.ActionLink("Add new Machine", "AddM", new { id = Model.EId })</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Add a new Machine</h4>

@using (Html.BeginForm())
{
  <p>Machine Name:</p>
  @Html.TextBoxFor(model => model.MName, new { @class = "form-control", placeholder="Required", required="required", style="width: 300px;"})

  <p>Engineers:</p>
  @Html.DropDownList("EId")


  <input type="submit" value="Add Machine" class="btn btn-default" />
}

<p>@Html.ActionLink("Show all machines", "Index")</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this machine?</h2>
 
@Html.DisplayFor(model => model.MName)

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
  @foreach(var join in Model.JoinEntities)
  {
    @using (Html.BeginForm("DeleteEngineer", "Machines"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
    }
  }
@Html.ActionLink("Back to Machine List", "Index")

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Machine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.MName): @Html.DisplayFor(model => model.MName)</h3>


@if(@Model.JoinEntities.Count == 0)
{
  <p>This machine is not used by any engineers</p>
}
else
{
  <h4>Engineers that use this machine:</h4>

  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Engineer.EName</li>
    @using (Html.BeginForm("DeleteEngineer", "Machines"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      <input type=:submit value="delete"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Add an Engineer", "AddE", new { id = Model.MId })</p>
<p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MId })</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MId })</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>

<h4>Edit this machine: @Html.DisplayFor(model => model.MName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MId)

    @Html.LabelFor(model => model.MName)
    @Html.EditorFor(model => model.MName)

    @Html.Label("Select Engineer")
    @Html.DropDownList("EId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@using System.ComponentModel.DataAnnotations;

@model List<Factory.Models.Machine>

<h1>Machines</h1>




@if (@Model.Count == 0)
{
  <h4>No Machines listed! Click <a>@Html.ActionLink("here", "Create")</a> to add a new machine.
	</h4>
} 

@foreach (Machine machine in Model)
{
  <li>@Html.ActionLink($"{machine.MName}", "Details", new { id = machine.MId })</li>
}

Factory/Views/Shared/Footer.cshtml
<h5>@Html.ActionLink("Home", "Index", "Home")</h5>
<div id="footer">© 2022 CAROLINE CERUSSI Factory App </div>

Factory/Views/Shared/Header.cshtml
<div id="header"><h1>Sillstringz Factory Log</h1></div>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Factory Stuff!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="/Users/carolinecerussi/Desktop/Factory/CSS">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;900&display=swap" rel="stylesheet">
  </head>
  
  <body>
    <main>
    @await Html.PartialAsync("Header")
     <hr />
    @RenderBody()
     <hr />
    @await Html.PartialAsync("Footer")
    </main>
  </body>
  
</html>  